### ISSUE TITLE
Request to Add FastLinQ QL45000 Series

### ISSUE THREAD

**Issue by hpeaj** [k8snetworkplumbingwg/community#13]
**Request to add Marvell FastLinQ QL45000 Series QLogic Corp. Vendor-id: 1077 as supported device for SR-IOV with K8s** 

Here is some of the changes we made to get this working 
1.	Created the SR-IOV Network CRD
$ kubectl create -f deployments/sriov-crd.yaml

Note: - Get the resource name (k8s.v1.cni.cncf.io/resourceName) by describe node as mentioned below 

 kubectl get node node1 -o json | jq '.status.allocatable'

  $ kubectl get node node1 -o json | jq '.status.allocatable'

{
    "allocable": {
      "cpu": "39430m",
      "ephemeral-storage": "86930620273",
      "hugepages-1Gi": "0",
      "hugepages-2Mi": "0",
      "marvell.com/marvell_sriov_dpdk": "3",
      "marvell.com/marvell_sriov_netdevice": "3",
      "memory": "121944076Ki",
      "pods": "250"
    }

shown below:
{
    "resourceList": [{
            "resourceName": "marvell_sriov_netdevice",
            "resourcePrefix": "marvell.com",
            "selectors": {
               "vendors": ["1077"],
               "devices": ["1664"],
               "drivers": ["qede","qed"]            
           }
        },
        {
            "resourceName": "marvell_sriov_dpdk",
            "resourcePrefix": "marvell.com",
            "selectors": {
                "vendors": ["1077"],
                "devices": ["1664"],
                "drivers": ["qede","qed"],
                "pfNames": ["ens3f0"],
                "needVhostNet": true            
          }
        }    

    ]
}
$ kubectl get node node1 -o json | jq '.status.allocatable'

{
    "allocable": {
      "cpu": "39430m",
      "ephemeral-storage": "86930620273",
      "hugepages-1Gi": "0",
      "hugepages-2Mi": "0",
      "marvell.com/marvell_sriov_dpdk": "3",
      "marvell.com/marvell_sriov_netdevice": "3",
      "memory": "121944076Ki",
      "pods": "250"
    }
Deploy test Pod connecting to pre-created SR-IOV network
$ kubectl create -f pod-tc1.yaml
pod "testpod1" created

$ kubectl get pods
NAME              READY     STATUS    RESTARTS   AGE
testpod1        	  1/1       Running   0          3s
Verify Pod network interfaces
$ kubectl exec -it testpod1 -- ip addr show

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
4: net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 9a:c0:0e:90:11:04 brd ff:ff:ff:ff:ff:ff
    inet 10.56.217.5/8 brd 10.255.255.255 scope global net1
       valid_lft forever preferred_lft forever
1246: eth0@if1247: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 26:f2:d1:a6:35:34 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.2.174/32 scope global eth0
       valid_lft forever preferred_lft forever
Verify Pod routing table
$ kubectl exec -it testpod1 -- route -n

Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.3.23    0.0.0.0         UG    0      0        0 eth0
10.0.0.0        0.0.0.0         255.0.0.0       U     0      0        0 net1
192.168.3.23    0.0.0.0         255.255.255.255 UH    0      0        0 eth0

kubectl get po -A --kubeconfig $u1 |grep -i multus
kube-system kube-multus-ds-64d9q 1/1 Running 0 2d19h
kube-system kube-multus-ds-c4cnj 1/1 Running 0 2d19h

kubectl get po -A --kubeconfig $u1 |grep -i sriov
default sriovpod1 1/1 Running 0 45h
kube-system kube-sriov-device-plugin-amd64-kxfrg 1/1 Running 0 2d19h
kube-system kube-sriov-device-plugin-amd64-mwqwg 1/1 Running 0 2d19h

[describepod.yaml.txt](https://github.com/k8snetworkplumbingwg/community/files/7911056/describepod.yaml.txt)
[sriov-crd-network-attach.yaml.txt](https://github.com/k8snetworkplumbingwg/community/files/7911057/sriov-crd-network-attach.yaml.txt)

Please could help with process and what info is required to list Marvell 
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:\Users\josepedw\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<link rel=themeData
href="file:///C:\Users\josepedw\AppData\Local\Temp\msohtmlclip1\01\clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:\Users\josepedw\AppData\Local\Temp\msohtmlclip1\01\clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in'>

Vendor
--
QLogic Corp.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:\Users\josepedw\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<link rel=themeData
href="file:///C:\Users\josepedw\AppData\Local\Temp\msohtmlclip1\01\clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:\Users\josepedw\AppData\Local\Temp\msohtmlclip1\01\clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in'>

Vendor ID
--
1077

</body>

</html>

</body>

</html>
![image](https://user-images.githubusercontent.com/55138250/150482813-2cd6e42f-c331-4290-ad42-63037332ee25.png)

HPE Synergy 6820C 25/50Gb Converged Network Adapter 
https://support.hpe.com/hpesc/public/docDisplay?docId=a00091480en_us&docLocale=en_US

**Comment by s1061123** [comment]
Hi,

This repository is for its community (managing members and so on), not sr-iov related repo.
As far as I looked, you want to add vendor id into sr-iov device plugin (and sr-iov network operator might be).

Could you bring this topic into each projects?

- https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin
- https://github.com/k8snetworkplumbingwg/sriov-network-operator
