### ISSUE TITLE
Community Slack link not working

### ISSUE THREAD

**Issue by tariq1890** [k8snetworkplumbingwg/community#17]
I am trying to join the Slack link provided in the `README.md`, but I get redirected to this page: https://intel-corp.herokuapp.com/

When I try this link instead: https://npwg-team.slack.com/, I am asked to register with an Intel email

I request the maintainers to provide clear instructions to join the NPWG community slack

**Comment by plwhite** [comment]
You do not need to have an Intel email to join that Slack group, but I agree that the link is wrong. I will submit a PR for that.

**Comment by maiqueb** [comment]
hey, the auto-invite link is not working, as reported in:
- https://github.com/k8snetworkplumbingwg/multus-cni/issues/1020#issuecomment-1521541274

Any clue on how to proceed ? @plwhite / @dougbtv / @s1061123
